export const DEFAULT_MOTIVATIONAL_QUOTES: string[] = [
  'Her gun atilan kucuk adimlar, buyuk degisimin temelidir.',
  'Motivasyon dalgalanir, disiplin seni hedefe tasir.',
  'Bugun zorlanman, yarin guclenmenin bedelidir.',
  'Baslamak icin hazir hissetmeyi bekleme.',
  'Kendinle yarisirsan her gun kazanan olursun.',
  'Basari, tekrar edilen dogru aliskanliklarin toplamidir.',
  'Yavas ilerlemek, hic ilerlememekten iyidir.',
  'Odaklandigin sey, hayatinin yonunu belirler.',
  'Mazeretler kisadir, sonuclar kalicidir.',
  'Her gorev, karakterini insa eden bir tugladir.',
  'Planin yoksa, baskasinin planina dahil olursun.',
  'Aksiyon netlik getirir, erteleme sis olusturur.',
  'Zor gunler, guclu insanlar yetistirir.',
  'Kalite, kimse bakmiyorken yaptigin sectir.',
  'Kaybetmek degil, vazgecmek gercek yenilgidir.',
  'Kendine verdigin sozleri tutmak ozguven dogurur.',
  'Korku genelde kapinin onundedir, odanin icinde degil.',
  'Bugun attigin adim, yarinin konforunu belirler.',
  'Tutarlilik, yetenekten daha uzun omurludur.',
  'Sikildigin yerde buyume baslar.',
  'Hedefler yazilinca niyet, plana donusur.',
  'Basari tesaduf degil, tercihlerin sonucudur.',
  'Bahane uretmek yerine cozum uret.',
  'Kendine saygin, gunluk rutininle olusur.',
  'Zihnini besleyen icerik, performansini belirler.',
  'Bir isi dogru yapmak, iki kez yapmaktan hizlidir.',
  'Ilerleme mukemmel degil, devamli olmaktir.',
  'Zamanin degeri, harcadigin yere gore olculur.',
  'Kucuk kazanclar birikince buyuk guc olur.',
  'Baslangiclar gosterissizdir, sonuclar konusur.',
  'Enerjini sikayetle degil, eylemle kullan.',
  'Kural basit: durma, duzelt, devam et.',
  'Iyi aliskanliklar sessizce hayat kurtarir.',
  'Gununu yonetmezsen, gun seni yonetir.',
  'Cozum odakli dusunce, hizi ikiye katlar.',
  'Hata yapmak normaldir, ayni hatada kalmak degil.',
  'Biriktirdigin emek, zor zamanda seni ayakta tutar.',
  'Kendine acik hedef koy, zihnin dagilmasin.',
  'Disiplin, gelecekteki ozgurlugun pesinatidir.',
  'Zor isleri once yap, gun hafiflesin.',
  'Odul degil, surec seni buyutur.',
  'Her tekrar, ustalik yolunda bir basamaktir.',
  'Baskilar gecicidir, kazandigin guc kalicidir.',
  'Yol uzun olabilir, ama her adim sayilir.',
  'Sikismis hissetmek, yeni sistem kurma sinyalidir.',
  'Netlik yoksa liste yap, belirsizlik azalir.',
  'Sakinlik, kriz aninda en buyuk avantajdir.',
  'Kendini kiyaslama, kendini gelistir.',
  'Calismak zorunda degilsin, gelismek istiyorsun.',
  'Iyi bir gun, iyi bir sabahla baslar.',
  'Birikimli emek, bir gecede sans gibi gorunur.',
  'Yuksek standartlar, yuksek sonuclar dogurur.',
  'Tempon dusse de yonun dogruysa sorun yok.',
  'Derin calisma, daginik cabadan daha degerlidir.',
  'Basariya en yakin an, vazgecmek istedigin andir.',
  'Kararsizlik, enerjiyi sessizce tuketir.',
  'Kendine liderlik edemeyen, baskasini yonetemez.',
  'Takvimindeki seyler, onceliklerinin gercek halidir.',
  'Iyi ekipler guven ve netlikten dogar.',
  'Her hayir, daha dogru bir evete yer acar.',
  'Ilerleme kaydi tut, motivasyonun geri gelir.',
  'Gunluk %1 iyilesme, yilin sonunda dev fark yaratir.',
  'Sistem kur, iradeye daha az yuklen.',
  'Hedefin buyukse, bahanen kucuk kalir.',
  'Gec kaldigini dusundugun an, ikinci en iyi baslangictir.',
  'Ogrenme hizi, rekabet avantajidir.',
  'Gerilim, buyume bolgesinin dogal parcasidir.',
  'Sorumluluk almak, guc kazandirir.',
  'Kisa vadeli rahatlik, uzun vadeli pismanlik dogurur.',
  'Oz disiplin, oz sayginin uygulamadaki halidir.',
  'Dusunceni degistir, davranisin degissin.',
  'Buyuk hedefler, sade aliskanliklarla kazanilir.',
  'Calisma masan, zihninin aynasidir.',
  'Karakter, zorlukta verdigin kararlarla yazilir.',
  'Iyi bir plan, kaygiyi azaltir.',
  'Net hedef, net performans getirir.',
  'Odak, daginik gucu tek noktada toplar.',
  'Her gun ayni saat calismak ritim kurar.',
  'Yaptigin isi sev, sevemiyorsan iyi yap.',
  'Zamanin yoksa, onceligin yoktur.',
  'Yorgunken bile devam etmek dayaniklilik kazandirir.',
  'Gecici hisler, kalici kararlari yonetmemeli.',
  'Basari, gorunmeyen hazirliklarda saklidir.',
  'Sikayet ettigin yerde sorumluluk al.',
  'Hizli olmak icin once net ol.',
  'Eforun yonu dogruysa, sonuc gecikse de gelir.',
  'Toparlanma hizin, performansinin parcasi.',
  'Daha iyi sorular, daha iyi sonuclar getirir.',
  'Kendine rakip olursan surekli gelisirsin.',
  'Moralin dusuk olabilir, standartlarin dusmesin.',
  'Bir isi bitirmek, motivasyonu yeniden uretir.',
  'Cesaret korkunun yoklugu degil, harekete gecmektir.',
  'Sade yasam, derin uretim icin alan acar.',
  'Rutinler, zor gunlerde seni korur.',
  'Yapilacaklar listesi kadar birakilacaklar listesi de onemlidir.',
  'Israrci ol, inatci degil; yontemi degistir, hedefi degil.',
  'Kesintisiz 30 dakika, daginik 3 saatten iyidir.',
  'Tutumun, yetenegin etkisini katlar.',
  'Hedefe ulasmanin sirri: yeniden baslamak.',
  'Baskasinin alkisini bekleme, kendi standardini belirle.',
  'Bugun guclu hissetmiyorsan da guclu davranabilirsin.',
  'Yapamadigina degil, bir sonraki adima odaklan.',
  'Net sinirlar, net enerji demektir.',
  'Ozellikle zor gunlerde temel rutine sadik kal.',
  'Iyi uyku, iyi kararlarin altyapisidir.',
  'Basari, dogru zamanda degil, dogru sekilde calisana gelir.',
  'Karsina cikan engeller, kapasiteni genisletmek icindir.',
  'Her tamamlanan gorev, zihninde yer acar.',
  'Disiplini bir ceza degil, kendine saygi olarak gor.',
  'Buyuk degisim, tekrar eden kucuk secimlerden dogar.',
  'Kaynaklarin kisitliysa yaraticiligin artar.',
  'Yol boyunca sabir, varista kalite getirir.',
  'Net iletisim, gereksiz yorgunlugu azaltir.',
  'Performans, niyetten cok davranisa bakar.',
  'Her gun bir adim, birikimli gucun formuludur.',
  'Uretkenlik daha cok degil, daha dogru sey yapmaktir.',
  'Zor kararlar karakteri, kolay kararlar konforu buyutur.',
  'Hedefin aciksa, daginiklik azalir.',
  'Dunyanin sesi kisilmaz, senin odagin guclenir.',
  'Emek saklanmaz; gecikir ama mutlaka gorunur.',
  'Iyi bir ekip, ayni amaca bakan farkli guclerdir.',
  'Kendi hikayeni yazmak icin once bugunu yonet.',
];
